export const APP_CONFIG = {
  MAX_QUESTION_LENGTH: 500,
  VISIBLE_HISTORY_INITIAL: 50,
  LOAD_MORE_INCREMENT: 25,
  SCROLL_THRESHOLD_PX: 10,
  SCROLL_BOTTOM_THRESHOLD_PX: 32,
  AUTO_SCROLL_DELAY_MS: 100,
  AUTO_SCROLL_ANIMATION_MS: 500,
  ACCESSIBILITY_ANNOUNCEMENT_THROTTLE_MS: 1000,
} as const;

